pcm/urls.py
from django.contrib import admin
from django.urls import include,path
from pcmapp.admin import admin_site
from django.views.generic import RedirectView

urlpatterns = [
    path('pcmapp/',include('pcmapp.urls')),
    path('admin/', admin.site.urls),
    path('pcmadmin/', admin_site.urls),
    path('member/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/pcmapp/', permanent=True)),

]

pcmapp/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'pcmapp'
urlpatterns = [
    #display list of members
    path('',views.IndexView.as_view(), name='index'),
    #get by  member
    path('member/view',views.MemberDetailView.as_view(), name='member-view'),
    path('member/list/', views.NewMemberListView.as_view(), name='member-list'),
    path('member/<int:pk>',views.NewMemberDetailView.as_view(), name='member-detail'),
    #display list of payees
    path('payment/',views.PaymentInYearView.as_view(),name='payment'),
    path('expiring/',views.ExpiringMembershipList.as_view(), name='expiring_members'),
    path('member/registration/',views.NewMemberRegistrationView.as_view(),name='newregistration'),
    path('member/registration/registrationsuccess/',views.RegistrationSuccess.as_view(),name='registrationsuccess'),
    #path('member/registration/car', views.NewCarRegistrationCreate.as_view(), name='newcarregistration'),
    path('member/sccheck',views.SCcheckView.as_view(),name='sccheck'),
    path('member/sccheckdetails/<int:pk>',views.SCcheckDetailView.as_view(),name='sccheckdetails'),
]
#    path('member/login', auth_views.login, name='login'),

pcmapp/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User,Group

# Create your models here.

class Member(models.Model):
    STATE_CHOICES = (
        ('JH','Johor'),
        ('KH','Kedah'),
        ('KN','Kelantan'),
        ('KL','Kuala Lumpur'),
        ('LA','Labuan'),
        ('ME','Melaka'),
        ('NS','Negeri Sembilan'),
        ('PH','Pahang'),
        ('PK','Perak'),
        ('PL','Perlis'),
        ('PG','Pulau Pinang'),
        ('PJ','Putrajaya'),
        ('SA','Sabah'),
        ('SK','Sarawak'),
        ('SL','Selangor'),
        ('TE','Terengganu'),
    )
    SOURCE_CHOICES = (
        ('FB','Facebook'),
        ('TW','Twitter'),
        ('SC','Service Center'),
        ('IN','Instagram'),
        ('RE','Referral'),
        ('WO','Word of Mouth'),
        ('OT','Other'),
        )

    member_name = models.CharField(max_length=200, verbose_name='Full Name')
    member_email = models.EmailField(max_length=200, verbose_name='Email Address')
    member_phone = models.CharField(max_length=20,verbose_name='Mobile Number')
    member_since = models.DateField(blank=True, null=True)
    member_birthdate = models.DateField(blank=True, null=True, verbose_name='Your Birthdate')
    member_address_state = models.CharField(max_length=2,choices=STATE_CHOICES,blank=True,null=True, verbose_name='Current Location (State)')
    member_address_postcode = models.CharField(max_length=5,blank=True,null=True, verbose_name = 'Postcode')
    member_on_chat = models.BooleanField(default=True,verbose_name = 'Would you like to be added to our WhatsApp Group?' )
    member_source = models.CharField(max_length=2,choices = SOURCE_CHOICES,blank=True,null=True,verbose_name = 'Where did you hear about us?')
    member_expiry_date = models.DateField(blank=True,null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.member_name

    def save(self, *args, **kwargs):
        for field_name in ['member_name']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.upper())
        r =  User.objects.filter(email=self.member_email)
        if (r.count() < 1):
            user = User.objects.create_user(self.member_email,self.member_email,'asdfgh123')
            user.save()
            g = Group.objects.get(name='Member')
            g.user_set.add(user)
            g.save()
            self.owner = user
        super(Member, self).save(*args, **kwargs)

    @property
    def is_expired(self):
        if self.member_expiry_date < date.today():
            return True
        return False

    def get_absolute_url(self):
        return reverse('member-detail',args=[str(self.id)] )

class MemberManager(models.Manager):
    @property
    def is_expiring_in_month(self):
        return self.get_queryset().filter(member_expiry_date__month = date.today().month)



"""
Function to build
1. create user when saving and link to member id
2. update expiry date based on payment date
3. display expiring records (within one month?)

"""
class Car(models.Model):
    PRIMARY_SEC_CHOICES = (
        (1,'Primary'),
        (2,'Secondary'),
        )
    member_id = models.ForeignKey(Member, on_delete=models.CASCADE)
    car_reg_no = models.CharField(max_length=20, verbose_name='Registration Number')
    car_model = models.CharField(max_length=20, verbose_name='Model')
    car_engine_chasis = models.CharField(max_length=20, verbose_name='Engine Chassis',blank=True,null=True)
    car_primary_sec = models.SmallIntegerField(blank=True,null=True,choices=PRIMARY_SEC_CHOICES, verbose_name='Primary/Secondary Car')
    car_status = models.BooleanField(default=True,verbose_name='Status')
    def __str__(self):
        return self.car_reg_no
    #def get_absolute_url(self):
    #    return reverse('pcmapp:index')
    def save(self, *args, **kwargs):
        for field_name in ['car_reg_no','car_model','car_engine_chasis']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.upper())
        for field_name in ['car_reg_no']:
            val =  getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.replace(" ",""))
        super(Car, self).save(*args, **kwargs)
"""
define secondary car insert
"""
class Payment(models.Model):
    PAYMENT_CHOICES= (
        ('1','New'),
        ('2','Renewal'),
        ('3','Supplementary'),
        )
    payment_car_reg_no = models.ForeignKey(Member,on_delete=models.CASCADE)
    payment_date = models.DateField(blank=True,verbose_name='Payment Date')
    payment_amount = models.IntegerField(verbose_name='Payment Amount')
    payment_type = models.CharField(max_length=1,choices = PAYMENT_CHOICES,verbose_name='Payment For')
    payment_receipt_image = models.FileField(upload_to='uploadreceipt',null=True,blank=True,verbose_name='Proof of Payment')
"""
update the expiry date when payment is made.
"""

pcmapp/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Member, Car, Payment




class NewMemberRegistrationForm(forms.ModelForm):
    #member_address_state = forms.ChoiceField(choices=STATE_CHOICES)
    class Meta:
        model = Member
        fields = ['member_name','member_email','member_phone','member_birthdate','member_address_state','member_address_postcode','member_on_chat','member_source']
        widgets = {
            'member_birthdate': forms.DateInput(attrs={'type': 'date', 'format' :'YYYY-MM-DD'}),
            'member_name' : forms.TextInput(attrs={'size':40}),
            'member_email' : forms.TextInput(attrs={'size':40}),
            'member_address_postcode' : forms.TextInput(attrs={'size':5}),
        }

class NewMemberCarRegistrationForm(forms.ModelForm):
    class Meta:
        model=Car
        fields = ['member_id','car_reg_no','car_model','car_engine_chasis']

CarRegistrationFormSet =  inlineformset_factory(Member,
    Car,
    fields = ['member_id','car_reg_no','car_model','car_engine_chasis','car_primary_sec'],
    extra=1)
PaymentFormSet = inlineformset_factory(Member,
    Payment,
    fields = ['payment_date','payment_amount','payment_type','payment_receipt_image'],
    extra=1,
    widgets = {'payment_date':forms.DateInput(attrs={'type': 'date', 'format' :'YYYY-MM-DD'})})

class SCCheckForm(forms.Form):
    car_reg_no = forms.CharField(label='Car Registration number', max_length=10)

    def clean_car_reg_no(self):
        car_reg_no = self.cleaned_data['car_reg_no']
        car_reg_no = car_reg_no.replace(" ","")
        try:
            obj = Car.objects.get(car_reg_no=car_reg_no)
            return car_reg_no
        except Car.DoesNotExist:
            raise forms.ValidationError('No record found')

pcmapp/views.py
from django.shortcuts import get_object_or_404, render
from django.db import transaction
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import NewMemberRegistrationForm,SCCheckForm, CarRegistrationFormSet,PaymentFormSet
from .models import Member,Payment,Car
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, Group
from django import template
from datetime import date

# Create your views here.

#def index(request):
 #   member = Member.objects.all()
  #  context =  {'member' : member}
   # return render(request,'pcmapp/index.html', context)

class IndexView(generic.ListView):
    template_name = 'pcmapp/index.html'
    context_object_name = 'member'
    paginate_by = 10
    def get_queryset(self):
        return Member.objects.all()

#get details of car no
#def querymember(request, member_car_no):
 #   owner = Member.objects.get(member_car_no = member_car_no)
 #   context = {'owner': owner}
 #   return render(request,'pcmapp/memberdetail.html',context)

class DetailView(generic.DetailView):
    template_name = 'pcmapp/memberdetail.html'
    model = Member
    context_object_name = 'member'
    queryset = Member.objects.filter()

class PaymentInYearView(generic.ListView):
    template_name = 'pcmapp/paymentlist.html'
    model = Payment,Member
    context_object_name = 'payment'
    def get_queryset(self):
        return Payment.objects.all()

class NewRegistrationCreate(CreateView):
    model = Member
    template_name = 'pcmapp/newregistration.html'
    fields = ['member_name','member_email','member_phone','member_birthdate','member_address_state','member_address_postcode','member_on_chat','member_source']
    def get_context_data(self, **kwargs):
       context = super(NewRegistrationCreate, self).get_context_data(**kwargs)
       return context


class NewCarRegistrationCreate(CreateView):
    model = Car
    template_name = 'pcmapp/newcarregistration.html'
    fields = ['car_reg_no','car_model','car_engine_chasis']
    sucess_url = 'pcmapp:index'
    def get_context_data(self, **kwargs):
       context = super(NewCarRegistrationCreate, self).get_context_data(**kwargs)
       return context

class NewMemberRegistrationView(CreateView):
    template_name = 'pcmapp/newregistration.html'
    model = Member
    form_class = NewMemberRegistrationForm
    success_url = 'registrationsuccess'
    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        car_form = CarRegistrationFormSet()
        receipt_form = PaymentFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  car_form=car_form,
                                  receipt_form=receipt_form))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        car_form = CarRegistrationFormSet(self.request.POST)
        receipt_form = PaymentFormSet(self.request.POST, self.request.FILES)
        if (form.is_valid() and car_form.is_valid() and receipt_form.is_valid()):
            return self.form_valid(form, car_form, receipt_form)
        else:
            return self.form_invalid(form, car_form, receipt_form)

    def form_valid(self, form, car_form, receipt_form):
        self.object = form.save()
        car_form.instance = self.object
        car_form.save()
        receipt_form.instance = self.object
        receipt_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, car_form,receipt_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  car_form=car_form,
                                  receipt_form=receipt_form))

class RegistrationSuccess(generic.TemplateView):
    template_name = 'pcmapp/registrationsuccess.html'

class SCcheckView(LoginRequiredMixin,generic.FormView):
    model=Car
    template_name = 'pcmapp/sccheck.html'
    form_class = SCCheckForm

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        #carid = get_object_or_404(Car, car_reg_no=request.POST.get('car_reg_no'))
        #self.success_url = 'sccheckdetails/%s' % carid.pk
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def form_valid(self,form):
        carid = Car.objects.get(car_reg_no=form.cleaned_data['car_reg_no'])
        self.success_url = 'sccheckdetails/%s' % carid.pk
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self,form):
        return self.render_to_response(
            self.get_context_data(form=form))

class SCcheckDetailView(LoginRequiredMixin,generic.DetailView):
    model = Car
    template_name = 'pcmapp/sccheck_detail.html'
    def get_context_data(self, **kwargs):
        context =  super(SCcheckDetailView, self).get_context_data(**kwargs)
        context['car'] = Car.objects.get(pk=self.kwargs.get('pk',None))
        context['member'] = Member.objects.get(id=context['car'].member_id.pk)
        return context


class NewMemberDetailView(generic.DetailView):
    model=Member
    template_name='pcmapp/member_detail.html'

class NewMemberListView(generic.ListView):
    model=Member
    template_name= 'pcmapp/new_member_list.html'
    paginate_by=20
    queryset =  Member.objects.all().filter(member_expiry_date__isnull=True)

class MemberDetailView(LoginRequiredMixin,generic.TemplateView):
    model=Member
    template_name='pcmapp/member_detail.html'

    def get_context_data(self,**kwargs):
        context = super(MemberDetailView,self).get_context_data(**kwargs)
        context['member']= Member.objects.get(owner=self.request.user)
        return context

class ExpiringMembershipList(generic.ListView):
    template_name = 'pcmapp/expiring_members.html'
    queryset = Member.objects.all().filter(member_expiry_date__month=date.today().month,member_expiry_date__year=date.today().year)

pcmapp/templates/pcmapp/base_site.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
  <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'pcmapp/style.css' %}" />

    {%block head%}

    {% endblock%}


</head>

<body>

  <div class="container-fluid">
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col"><h1>Peugeot Club Malaysia</h1></th>
            <th scope="col"><img src="{% static 'pcmapp/logo.jpeg' %}" alt="Generic placeholder image" height=75px align=right></th>
            </tr>
        </thead>
    </table>

    <div class="row">
      <div class="col-sm-3">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'pcmapp:index' %}">Home</a></li>
          <li><a href="{% url 'pcmapp:newregistration' %}">New Member Registrations</a></li>
          {% if user.is_authenticated %}
          {%load pcm_extras%}
          {% if request.user|has_group:"Member" %}
            <li><a href="{%url 'pcmapp:member-view' %}">Member - View Details</a></li>
          {% else %}
          {% endif %}
          {% if request.user|has_group:"PCM Admin" %}
            <li><a href="/pcmadmin">Admin Login</a></li>
            <li><a href="{% url 'pcmapp:expiring_members'%}">Expring Members</a></li>
            <li><a href="{% url 'pcmapp:member-list' %}">Admin-View New Registration</a></li>
          {% else %}
          {% endif %}



          {% if request.user|has_group:"Service Center" %}
            <li><a href="{% url 'pcmapp:sccheck' %}">SC Buddies Query</a></li>
          {% else %}
          {% endif %}

            {%endif%}
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}

      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-9 ">
      {% block content %}{% endblock %}
      {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
  <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

</body>
</html>

pcmapp/templates/pcmapp/expiring_members.html
{%extends "pcmapp/base_site.html"%}
{%block content%}This is the page to display the expiring members.
<h1>New Member List</h1>
{%if object_list%}
<table class="table">
    <thead><tr>
        <th>Member name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Expiry Date</th>
        </tr>
</thead>

    {%for member in object_list %}
        <tr>
          <td><a href="/pcmapp/member/{{member.pk}}">{{member.member_name}}</a></td>
          <td>{{member.member_email}}</td>
          <td>{{member.member_phone}}</td>
          <td>{{member.member_expiry_date}}</td>
        </tr>
    {%endfor%}
    {%else %}
    <p>No memberships expiring this month. </p>

</table>
{% endif%}
{%endblock%}

pcmapp/templates/pcmapp/index.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}
    <h1> Welcome to the Peugeot Club Malaysia online membership site</h1>
    If you are a new member please click on the New Member Registration on the left panel
    If you are an existing member please click on the Member Login
{% block pagination %}{%endblock%}
{% endblock %}

pcmapp/templates/pcmapp/makepaymentform.html
Member make payment
1. Payment intgration with M2U etc.
2. Upload Payment information if done link to a car number
3.

pcmapp/templates/pcmapp/member_detail.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}

<h1>Member detail view</h1>
{{member.pk}}
Member name: {{ member.member_name}}</br>
Membership expiry: {{member.member_expiry_date}}

{% endblock %}

pcmapp/templates/pcmapp/member_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>


pcmapp/templates/pcmapp/memberdetail.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}

<h1>Member detail view</h1>
Member car no.: {{ member.member_car_no }}</br>
Member name: {{ member.member_name}}</br>
Membership expiry: {{member.member_expiry_date}}

{% endblock %}

pcmapp/templates/pcmapp/new_member_list.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}
    <h1>New Member List</h1>
    {%if object_list%}
    <table class="table">
        <thead><tr>
            <th>Member name</th>
            <th>Email</th>
            <th>Phone</th>
            </tr>
    </thead>

        {%for member in object_list %}
            <tr>
              <td><a href="/pcmapp/member/{{member.pk}}">{{member.member_name}}</a></td>
              <td>{{member.member_email}}</td>
              <td>{{member.member_phone}}</td>
            </tr>
        {%endfor%}
        {%else %}
        <p>No new member registrations. </p>

    </table>
    {% endif%}

{% endblock %}

pcmapp/templates/pcmapp/newcarregistration.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}
<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD'
        });
    });
</script>
<h1>New Registration</h1>
<form method="POST" action="{% url 'pcmapp:newcarregistration' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Register'>
</form>

{% endblock %}

pcmapp/templates/pcmapp/newregistration.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block head %}
{% load static %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $('.inline.{{ car_form.prefix }}').formset({
                prefix: '{{ car_form.prefix }}',
            });
            $('.inline.{{ reciept_form.prefix }}').formset({
                prefix: '{{ reciept_form.prefix }}',
            });
        });
    </script>


{%endblock%}
{% block content %}

<h1>New Member Registration</h1>
<h2>Member Details</h2>
<p>Please key in your personal details in the section below as accurately as possible.</p>
<form method="POST" enctype="multipart/form-data" action="{% url 'pcmapp:newregistration' %}" class="viewform">{% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>

    <fieldset>
        <h2>Car details</h2>
        <p>Please key in your car details. You may enter up to 2 cars at any time.</p>
        {{ car_form.management_form }}
        {{ car_form.non_form_errors }}
        {% for form in car_form %}
                    {{ form.id }}
                    <div class="inline {{ car_form.prefix }}">
                        {{ form.car_reg_no.errors }}
                        {{ form.car_reg_no.label_tag }}
                        {{ form.car_reg_no }}
                        {{ form.car_model.errors }}
                        {{ form.car_model.label_tag }}
                        {{ form.car_model }}
                        {{ form.car_engine_chasis.errors }}
                        {{ form.car_engine_chasis.label_tag }}
                        {{ form.car_engine_chasis }}
                        {{ form.car_primary_sec.errors }}
                        {{ form.car_primary_sec.label_tag }}
                        {{ form.car_primary_sec }}

                    </div>
                {% endfor %}
        <h2>Payment details</h2>
        <p>Please key in your payment details.</p>
        {{ receipt_form.management_form }}
        {{ receipt_form.non_form_errors }}
        {% for form in receipt_form %}
                    {{ form.id }}
                    <div class="inline {{ reciept_form.prefix }}">
                        {{ form.payment_date.errors }}
                        {{ form.payment_date.label_tag }}
                        {{ form.payment_date }}
                        {{ form.payment_amount.errors }}
                        {{ form.payment_amount.label_tag }}
                        {{ form.payment_amount }}
                        {{ form.payment_type.errors }}
                        {{ form.payment_type.label_tag }}
                        {{ form.payment_type }}
                        {{ form.payment_receipt_image.errors }}
                        {{ form.payment_receipt_image.label_tag }}
                        {{ form.payment_receipt_image }}

                    </div>
                {% endfor %}

    </fieldset>

    <input type='submit' name='_submit' value='Register' class="btn btn-primary btn-lg">
</form>

{% endblock %}

pcmapp/templates/pcmapp/paymentlist.html
 Payess detail

 <table>
         <tr>
        <th>ID</th>
        <th>Member Name</th>
        <th>Paid date </th>

    </tr>
    {% for payee in payment %}
    <tr>
        <td>{{payee.id}}</td>
        <td>{{payee.member__member_name}}</td>
        <td>{{payee.payment_receipt_date}}</td>

    </tr>

    {% endfor %}
    </table>

pcmapp/templates/pcmapp/registrationsuccess.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}
    <h1> Welcome to the Peugeot Club Malaysia online membership site</h1>
    <p>We have received your registration information and our admins will verify and update you via email within the next 48 hours.
    <br> <h3>Welcome to the Club!</h3> </p>
{% block pagination %}{%endblock%}
{% endblock %}

pcmapp/templates/pcmapp/sccheck.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}

<h1>SC Check</h1>
<form method="POST" action="{% url 'pcmapp:sccheck' %}">
    {% csrf_token %}
    {{ form.management_form }}
    {{ form.non_form_errors }}
    {{ form }}
    <input type='submit' value='Search'>
</form>

{% endblock %}

pcmapp/templates/pcmapp/sccheck_detail.html
{% extends "pcmapp/base_site.html" %}
{% block title %}<title>Peugeot Club Malaysia</title>{% endblock %}
{% block content %}

{%if car%}
<h1>Member detail view</h1>
    <p>Car number: {{car.car_reg_no}}</p>
    <p>Name: {{member.member_name}}</p>
    <p class="{% if member.is_expired%} text-danger {%else%} text-success{%endif%}">Expiry Date:{{member.member_expiry_date}}</p>
    <p>Phone: {{member.member_phone}}</p>
    <p>Email: {{member.member_email}}</p>
{%else%}
<p>No members found</p>
{%endif%}
{% endblock %}